on:
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:22.7.0-alpine3.20
    steps:
      - run: corepack enable
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm test

  audit:
    runs-on: ubuntu-latest
    container: node:22.7.0-alpine3.20
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm audit --audit-level high
